FROM docker.io/library/maven:3.9-eclipse-temurin-22 AS build

WORKDIR /build

COPY pom.xml /build/pom.xml
COPY src /build/src

RUN mvn clean package -DskipTests


FROM docker.io/library/eclipse-temurin:22-jre

WORKDIR /app

COPY --from=build /build/target/programme-repository-1.0.0.jar /app/app.jar

EXPOSE 8003

ENTRYPOINT ["java", "-jar", "/app/app.jar"]